server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location /assets/ {
    try_files $uri =404;
    access_log off;
    expires 1y;
    add_header Cache-Control "public, immutable";
  }

  location /admin/assets/ {
    alias /usr/share/nginx/html/assets/;
    access_log off;
    expires 1y;
    add_header Cache-Control "public, immutable";
  }

    location /admin/icons/ {
    alias /usr/share/nginx/html/icons/;
    access_log off;
    expires 1y;
    add_header Cache-Control "public, max-age=31536000, immutable";
  }

  location = /admin {
    return 308 /admin/;
  }

  location /admin/ {
    rewrite ^/admin/?(.*)$ /$1 break;
    try_files $uri $uri/ /index.html;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
