/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as SubmitManagementRouteImport } from './routes/submit-management'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DiveDraftsRouteImport } from './routes/dive-drafts'
import { Route as DiveCreateRouteImport } from './routes/dive-create'
import { Route as IndexRouteImport } from './routes/index'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitManagementRoute = SubmitManagementRouteImport.update({
  id: '/submit-management',
  path: '/submit-management',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DiveDraftsRoute = DiveDraftsRouteImport.update({
  id: '/dive-drafts',
  path: '/dive-drafts',
  getParentRoute: () => rootRouteImport,
} as any)
const DiveCreateRoute = DiveCreateRouteImport.update({
  id: '/dive-create',
  path: '/dive-create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dive-create': typeof DiveCreateRoute
  '/dive-drafts': typeof DiveDraftsRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/submit-management': typeof SubmitManagementRoute
  '/test': typeof TestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dive-create': typeof DiveCreateRoute
  '/dive-drafts': typeof DiveDraftsRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/submit-management': typeof SubmitManagementRoute
  '/test': typeof TestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dive-create': typeof DiveCreateRoute
  '/dive-drafts': typeof DiveDraftsRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/submit-management': typeof SubmitManagementRoute
  '/test': typeof TestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dive-create'
    | '/dive-drafts'
    | '/home'
    | '/login'
    | '/profile'
    | '/register'
    | '/submit-management'
    | '/test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dive-create'
    | '/dive-drafts'
    | '/home'
    | '/login'
    | '/profile'
    | '/register'
    | '/submit-management'
    | '/test'
  id:
    | '__root__'
    | '/'
    | '/dive-create'
    | '/dive-drafts'
    | '/home'
    | '/login'
    | '/profile'
    | '/register'
    | '/submit-management'
    | '/test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiveCreateRoute: typeof DiveCreateRoute
  DiveDraftsRoute: typeof DiveDraftsRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SubmitManagementRoute: typeof SubmitManagementRoute
  TestRoute: typeof TestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit-management': {
      id: '/submit-management'
      path: '/submit-management'
      fullPath: '/submit-management'
      preLoaderRoute: typeof SubmitManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dive-drafts': {
      id: '/dive-drafts'
      path: '/dive-drafts'
      fullPath: '/dive-drafts'
      preLoaderRoute: typeof DiveDraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dive-create': {
      id: '/dive-create'
      path: '/dive-create'
      fullPath: '/dive-create'
      preLoaderRoute: typeof DiveCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiveCreateRoute: DiveCreateRoute,
  DiveDraftsRoute: DiveDraftsRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SubmitManagementRoute: SubmitManagementRoute,
  TestRoute: TestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
