/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as ReviewSubmissionIdRouteImport } from './routes/review.$submissionId'
import { Route as DashboardSpeciesCreateRouteImport } from './routes/dashboard.speciesCreate'
import { Route as DashboardCreateRouteImport } from './routes/dashboard.create'
import { Route as DashboardAreaIdRouteImport } from './routes/dashboard.$areaId'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/profile.lazy').then((d) => d.Route))
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/home.lazy').then((d) => d.Route))
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/dashboard.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard.index.lazy').then((d) => d.Route),
)
const ReviewSubmissionIdRoute = ReviewSubmissionIdRouteImport.update({
  id: '/review/$submissionId',
  path: '/review/$submissionId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/review.$submissionId.lazy').then((d) => d.Route),
)
const DashboardSpeciesCreateRoute = DashboardSpeciesCreateRouteImport.update({
  id: '/speciesCreate',
  path: '/speciesCreate',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard.speciesCreate.lazy').then((d) => d.Route),
)
const DashboardCreateRoute = DashboardCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard.create.lazy').then((d) => d.Route),
)
const DashboardAreaIdRoute = DashboardAreaIdRouteImport.update({
  id: '/$areaId',
  path: '/$areaId',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard.$areaId.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/dashboard/$areaId': typeof DashboardAreaIdRoute
  '/dashboard/create': typeof DashboardCreateRoute
  '/dashboard/speciesCreate': typeof DashboardSpeciesCreateRoute
  '/review/$submissionId': typeof ReviewSubmissionIdRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/dashboard/$areaId': typeof DashboardAreaIdRoute
  '/dashboard/create': typeof DashboardCreateRoute
  '/dashboard/speciesCreate': typeof DashboardSpeciesCreateRoute
  '/review/$submissionId': typeof ReviewSubmissionIdRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/dashboard/$areaId': typeof DashboardAreaIdRoute
  '/dashboard/create': typeof DashboardCreateRoute
  '/dashboard/speciesCreate': typeof DashboardSpeciesCreateRoute
  '/review/$submissionId': typeof ReviewSubmissionIdRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/home'
    | '/login'
    | '/profile'
    | '/dashboard/$areaId'
    | '/dashboard/create'
    | '/dashboard/speciesCreate'
    | '/review/$submissionId'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/login'
    | '/profile'
    | '/dashboard/$areaId'
    | '/dashboard/create'
    | '/dashboard/speciesCreate'
    | '/review/$submissionId'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/home'
    | '/login'
    | '/profile'
    | '/dashboard/$areaId'
    | '/dashboard/create'
    | '/dashboard/speciesCreate'
    | '/review/$submissionId'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ReviewSubmissionIdRoute: typeof ReviewSubmissionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/review/$submissionId': {
      id: '/review/$submissionId'
      path: '/review/$submissionId'
      fullPath: '/review/$submissionId'
      preLoaderRoute: typeof ReviewSubmissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/speciesCreate': {
      id: '/dashboard/speciesCreate'
      path: '/speciesCreate'
      fullPath: '/dashboard/speciesCreate'
      preLoaderRoute: typeof DashboardSpeciesCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/create': {
      id: '/dashboard/create'
      path: '/create'
      fullPath: '/dashboard/create'
      preLoaderRoute: typeof DashboardCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/$areaId': {
      id: '/dashboard/$areaId'
      path: '/$areaId'
      fullPath: '/dashboard/$areaId'
      preLoaderRoute: typeof DashboardAreaIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAreaIdRoute: typeof DashboardAreaIdRoute
  DashboardCreateRoute: typeof DashboardCreateRoute
  DashboardSpeciesCreateRoute: typeof DashboardSpeciesCreateRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAreaIdRoute: DashboardAreaIdRoute,
  DashboardCreateRoute: DashboardCreateRoute,
  DashboardSpeciesCreateRoute: DashboardSpeciesCreateRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ReviewSubmissionIdRoute: ReviewSubmissionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
