/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewSubmissionIdRouteImport } from './routes/review.$submissionId'
import { Route as DashboardSpeciesCreateRouteImport } from './routes/dashboard.speciesCreate'
import { Route as DashboardCreateRouteImport } from './routes/dashboard.create'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewSubmissionIdRoute = ReviewSubmissionIdRouteImport.update({
  id: '/review/$submissionId',
  path: '/review/$submissionId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSpeciesCreateRoute = DashboardSpeciesCreateRouteImport.update({
  id: '/speciesCreate',
  path: '/speciesCreate',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCreateRoute = DashboardCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/dashboard/create': typeof DashboardCreateRoute
  '/dashboard/speciesCreate': typeof DashboardSpeciesCreateRoute
  '/review/$submissionId': typeof ReviewSubmissionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/dashboard/create': typeof DashboardCreateRoute
  '/dashboard/speciesCreate': typeof DashboardSpeciesCreateRoute
  '/review/$submissionId': typeof ReviewSubmissionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/dashboard/create': typeof DashboardCreateRoute
  '/dashboard/speciesCreate': typeof DashboardSpeciesCreateRoute
  '/review/$submissionId': typeof ReviewSubmissionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/home'
    | '/login'
    | '/dashboard/create'
    | '/dashboard/speciesCreate'
    | '/review/$submissionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/home'
    | '/login'
    | '/dashboard/create'
    | '/dashboard/speciesCreate'
    | '/review/$submissionId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/home'
    | '/login'
    | '/dashboard/create'
    | '/dashboard/speciesCreate'
    | '/review/$submissionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  ReviewSubmissionIdRoute: typeof ReviewSubmissionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$submissionId': {
      id: '/review/$submissionId'
      path: '/review/$submissionId'
      fullPath: '/review/$submissionId'
      preLoaderRoute: typeof ReviewSubmissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/speciesCreate': {
      id: '/dashboard/speciesCreate'
      path: '/speciesCreate'
      fullPath: '/dashboard/speciesCreate'
      preLoaderRoute: typeof DashboardSpeciesCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/create': {
      id: '/dashboard/create'
      path: '/create'
      fullPath: '/dashboard/create'
      preLoaderRoute: typeof DashboardCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardCreateRoute: typeof DashboardCreateRoute
  DashboardSpeciesCreateRoute: typeof DashboardSpeciesCreateRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCreateRoute: DashboardCreateRoute,
  DashboardSpeciesCreateRoute: DashboardSpeciesCreateRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  ReviewSubmissionIdRoute: ReviewSubmissionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
